/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiScheduleIndexRouteImport } from './routes/api/schedule/index'
import { Route as ApiDoctorScheduleIndexRouteImport } from './routes/api/doctor-schedule/index'
import { Route as ApiUserCreatePatientRouteImport } from './routes/api/user/create-patient'
import { Route as ApiUserCreateDoctorRouteImport } from './routes/api/user/create-doctor'
import { Route as ApiUserCreateAdminRouteImport } from './routes/api/user/create-admin'
import { Route as ApiScheduleIdRouteImport } from './routes/api/schedule/$id'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScheduleIndexRoute = ApiScheduleIndexRouteImport.update({
  id: '/api/schedule/',
  path: '/api/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorScheduleIndexRoute = ApiDoctorScheduleIndexRouteImport.update({
  id: '/api/doctor-schedule/',
  path: '/api/doctor-schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreatePatientRoute = ApiUserCreatePatientRouteImport.update({
  id: '/api/user/create-patient',
  path: '/api/user/create-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreateDoctorRoute = ApiUserCreateDoctorRouteImport.update({
  id: '/api/user/create-doctor',
  path: '/api/user/create-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreateAdminRoute = ApiUserCreateAdminRouteImport.update({
  id: '/api/user/create-admin',
  path: '/api/user/create-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScheduleIdRoute = ApiScheduleIdRouteImport.update({
  id: '/api/schedule/$id',
  path: '/api/schedule/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dev/': typeof DevIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/schedule/$id': typeof ApiScheduleIdRoute
  '/api/user/create-admin': typeof ApiUserCreateAdminRoute
  '/api/user/create-doctor': typeof ApiUserCreateDoctorRoute
  '/api/user/create-patient': typeof ApiUserCreatePatientRoute
  '/api/doctor-schedule/': typeof ApiDoctorScheduleIndexRoute
  '/api/schedule/': typeof ApiScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dev': typeof DevIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/schedule/$id': typeof ApiScheduleIdRoute
  '/api/user/create-admin': typeof ApiUserCreateAdminRoute
  '/api/user/create-doctor': typeof ApiUserCreateDoctorRoute
  '/api/user/create-patient': typeof ApiUserCreatePatientRoute
  '/api/doctor-schedule': typeof ApiDoctorScheduleIndexRoute
  '/api/schedule': typeof ApiScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dev/': typeof DevIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/schedule/$id': typeof ApiScheduleIdRoute
  '/api/user/create-admin': typeof ApiUserCreateAdminRoute
  '/api/user/create-doctor': typeof ApiUserCreateDoctorRoute
  '/api/user/create-patient': typeof ApiUserCreatePatientRoute
  '/api/doctor-schedule/': typeof ApiDoctorScheduleIndexRoute
  '/api/schedule/': typeof ApiScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/api/health'
    | '/dev/'
    | '/api/auth/login'
    | '/api/schedule/$id'
    | '/api/user/create-admin'
    | '/api/user/create-doctor'
    | '/api/user/create-patient'
    | '/api/doctor-schedule/'
    | '/api/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/api/health'
    | '/dev'
    | '/api/auth/login'
    | '/api/schedule/$id'
    | '/api/user/create-admin'
    | '/api/user/create-doctor'
    | '/api/user/create-patient'
    | '/api/doctor-schedule'
    | '/api/schedule'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/api/health'
    | '/dev/'
    | '/api/auth/login'
    | '/api/schedule/$id'
    | '/api/user/create-admin'
    | '/api/user/create-doctor'
    | '/api/user/create-patient'
    | '/api/doctor-schedule/'
    | '/api/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DevIndexRoute: typeof DevIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiScheduleIdRoute: typeof ApiScheduleIdRoute
  ApiUserCreateAdminRoute: typeof ApiUserCreateAdminRoute
  ApiUserCreateDoctorRoute: typeof ApiUserCreateDoctorRoute
  ApiUserCreatePatientRoute: typeof ApiUserCreatePatientRoute
  ApiDoctorScheduleIndexRoute: typeof ApiDoctorScheduleIndexRoute
  ApiScheduleIndexRoute: typeof ApiScheduleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule/': {
      id: '/api/schedule/'
      path: '/api/schedule'
      fullPath: '/api/schedule/'
      preLoaderRoute: typeof ApiScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor-schedule/': {
      id: '/api/doctor-schedule/'
      path: '/api/doctor-schedule'
      fullPath: '/api/doctor-schedule/'
      preLoaderRoute: typeof ApiDoctorScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/create-patient': {
      id: '/api/user/create-patient'
      path: '/api/user/create-patient'
      fullPath: '/api/user/create-patient'
      preLoaderRoute: typeof ApiUserCreatePatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/create-doctor': {
      id: '/api/user/create-doctor'
      path: '/api/user/create-doctor'
      fullPath: '/api/user/create-doctor'
      preLoaderRoute: typeof ApiUserCreateDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/create-admin': {
      id: '/api/user/create-admin'
      path: '/api/user/create-admin'
      fullPath: '/api/user/create-admin'
      preLoaderRoute: typeof ApiUserCreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule/$id': {
      id: '/api/schedule/$id'
      path: '/api/schedule/$id'
      fullPath: '/api/schedule/$id'
      preLoaderRoute: typeof ApiScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  DevIndexRoute: DevIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiScheduleIdRoute: ApiScheduleIdRoute,
  ApiUserCreateAdminRoute: ApiUserCreateAdminRoute,
  ApiUserCreateDoctorRoute: ApiUserCreateDoctorRoute,
  ApiUserCreatePatientRoute: ApiUserCreatePatientRoute,
  ApiDoctorScheduleIndexRoute: ApiDoctorScheduleIndexRoute,
  ApiScheduleIndexRoute: ApiScheduleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
