/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DoctorIdRouteImport } from './routes/doctor/$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardPatientRouteRouteImport } from './routes/dashboard/patient/route'
import { Route as DashboardDoctorRouteRouteImport } from './routes/dashboard/doctor/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardPatientIndexRouteImport } from './routes/dashboard/patient/index'
import { Route as DashboardDoctorIndexRouteImport } from './routes/dashboard/doctor/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as ApiWeeklyAvailabilityIndexRouteImport } from './routes/api/weekly-availability/index'
import { Route as ApiScheduleIndexRouteImport } from './routes/api/schedule/index'
import { Route as ApiReviewIndexRouteImport } from './routes/api/review/index'
import { Route as ApiPrescriptionIndexRouteImport } from './routes/api/prescription/index'
import { Route as ApiPaymentIndexRouteImport } from './routes/api/payment/index'
import { Route as ApiPatientIndexRouteImport } from './routes/api/patient/index'
import { Route as ApiMetadataIndexRouteImport } from './routes/api/metadata/index'
import { Route as ApiDoctorIndexRouteImport } from './routes/api/doctor/index'
import { Route as ApiDoctorScheduleIndexRouteImport } from './routes/api/doctor-schedule/index'
import { Route as ApiAppointmentIndexRouteImport } from './routes/api/appointment/index'
import { Route as ApiAdminIndexRouteImport } from './routes/api/admin/index'
import { Route as DashboardPatientReviewsRouteImport } from './routes/dashboard/patient/reviews'
import { Route as DashboardPatientPaymentSuccessRouteImport } from './routes/dashboard/patient/payment-success'
import { Route as DashboardPatientPaymentHistoryRouteImport } from './routes/dashboard/patient/payment-history'
import { Route as DashboardPatientPaymentCancelRouteImport } from './routes/dashboard/patient/payment-cancel'
import { Route as DashboardPatientMyPrescriptionsRouteImport } from './routes/dashboard/patient/my-prescriptions'
import { Route as DashboardPatientMyAppointmentsRouteImport } from './routes/dashboard/patient/my-appointments'
import { Route as DashboardPatientHealthRecordsRouteImport } from './routes/dashboard/patient/health-records'
import { Route as DashboardPatientBookAppointmentRouteImport } from './routes/dashboard/patient/book-appointment'
import { Route as DashboardDoctorPrescriptionsRouteImport } from './routes/dashboard/doctor/prescriptions'
import { Route as DashboardDoctorMySchedulesRouteImport } from './routes/dashboard/doctor/my-schedules'
import { Route as DashboardDoctorAppointmentsRouteImport } from './routes/dashboard/doctor/appointments'
import { Route as DashboardAdminSpecialitiesManagementRouteImport } from './routes/dashboard/admin/specialities-management'
import { Route as DashboardAdminSchedulesManagementRouteImport } from './routes/dashboard/admin/schedules-management'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard/admin/payments'
import { Route as DashboardAdminPatientsManagementRouteImport } from './routes/dashboard/admin/patients-management'
import { Route as DashboardAdminDoctorsManagementRouteImport } from './routes/dashboard/admin/doctors-management'
import { Route as DashboardAdminAppointmentsManagementRouteImport } from './routes/dashboard/admin/appointments-management'
import { Route as DashboardAdminAdminsManagementRouteImport } from './routes/dashboard/admin/admins-management'
import { Route as ApiWeeklyAvailabilityGenerateRouteImport } from './routes/api/weekly-availability/generate'
import { Route as ApiWeeklyAvailabilityCancelRouteImport } from './routes/api/weekly-availability/cancel'
import { Route as ApiUserCreatePatientRouteImport } from './routes/api/user/create-patient'
import { Route as ApiUserCreateDoctorRouteImport } from './routes/api/user/create-doctor'
import { Route as ApiUserCreateAdminRouteImport } from './routes/api/user/create-admin'
import { Route as ApiScheduleIdRouteImport } from './routes/api/schedule/$id'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api/payment/webhook'
import { Route as ApiPaymentVerifyRouteImport } from './routes/api/payment/verify'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiPatientProfileRouteImport } from './routes/api/patient/profile'
import { Route as ApiPatientIdRouteImport } from './routes/api/patient/$id'
import { Route as ApiDoctorSpecializationsRouteImport } from './routes/api/doctor/specializations'
import { Route as ApiDoctorProfileRouteImport } from './routes/api/doctor/profile'
import { Route as ApiDoctorIdRouteImport } from './routes/api/doctor/$id'
import { Route as ApiDoctorScheduleAvailableRouteImport } from './routes/api/doctor-schedule/available'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAppointmentIdRouteImport } from './routes/api/appointment/$id'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAdminProfileRouteImport } from './routes/api/admin/profile'
import { Route as ApiAdminIdRouteImport } from './routes/api/admin/$id'
import { Route as ApiPublicLandingDataIndexRouteImport } from './routes/api/public/landing-data/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientRouteRoute = DashboardPatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDoctorRouteRoute = DashboardDoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPatientIndexRoute = DashboardPatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPatientRouteRoute,
} as any)
const DashboardDoctorIndexRoute = DashboardDoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDoctorRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const ApiWeeklyAvailabilityIndexRoute =
  ApiWeeklyAvailabilityIndexRouteImport.update({
    id: '/api/weekly-availability/',
    path: '/api/weekly-availability/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScheduleIndexRoute = ApiScheduleIndexRouteImport.update({
  id: '/api/schedule/',
  path: '/api/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewIndexRoute = ApiReviewIndexRouteImport.update({
  id: '/api/review/',
  path: '/api/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrescriptionIndexRoute = ApiPrescriptionIndexRouteImport.update({
  id: '/api/prescription/',
  path: '/api/prescription/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentIndexRoute = ApiPaymentIndexRouteImport.update({
  id: '/api/payment/',
  path: '/api/payment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatientIndexRoute = ApiPatientIndexRouteImport.update({
  id: '/api/patient/',
  path: '/api/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataIndexRoute = ApiMetadataIndexRouteImport.update({
  id: '/api/metadata/',
  path: '/api/metadata/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorIndexRoute = ApiDoctorIndexRouteImport.update({
  id: '/api/doctor/',
  path: '/api/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorScheduleIndexRoute = ApiDoctorScheduleIndexRouteImport.update({
  id: '/api/doctor-schedule/',
  path: '/api/doctor-schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentIndexRoute = ApiAppointmentIndexRouteImport.update({
  id: '/api/appointment/',
  path: '/api/appointment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIndexRoute = ApiAdminIndexRouteImport.update({
  id: '/api/admin/',
  path: '/api/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientReviewsRoute = DashboardPatientReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardPatientRouteRoute,
} as any)
const DashboardPatientPaymentSuccessRoute =
  DashboardPatientPaymentSuccessRouteImport.update({
    id: '/payment-success',
    path: '/payment-success',
    getParentRoute: () => DashboardPatientRouteRoute,
  } as any)
const DashboardPatientPaymentHistoryRoute =
  DashboardPatientPaymentHistoryRouteImport.update({
    id: '/payment-history',
    path: '/payment-history',
    getParentRoute: () => DashboardPatientRouteRoute,
  } as any)
const DashboardPatientPaymentCancelRoute =
  DashboardPatientPaymentCancelRouteImport.update({
    id: '/payment-cancel',
    path: '/payment-cancel',
    getParentRoute: () => DashboardPatientRouteRoute,
  } as any)
const DashboardPatientMyPrescriptionsRoute =
  DashboardPatientMyPrescriptionsRouteImport.update({
    id: '/my-prescriptions',
    path: '/my-prescriptions',
    getParentRoute: () => DashboardPatientRouteRoute,
  } as any)
const DashboardPatientMyAppointmentsRoute =
  DashboardPatientMyAppointmentsRouteImport.update({
    id: '/my-appointments',
    path: '/my-appointments',
    getParentRoute: () => DashboardPatientRouteRoute,
  } as any)
const DashboardPatientHealthRecordsRoute =
  DashboardPatientHealthRecordsRouteImport.update({
    id: '/health-records',
    path: '/health-records',
    getParentRoute: () => DashboardPatientRouteRoute,
  } as any)
const DashboardPatientBookAppointmentRoute =
  DashboardPatientBookAppointmentRouteImport.update({
    id: '/book-appointment',
    path: '/book-appointment',
    getParentRoute: () => DashboardPatientRouteRoute,
  } as any)
const DashboardDoctorPrescriptionsRoute =
  DashboardDoctorPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => DashboardDoctorRouteRoute,
  } as any)
const DashboardDoctorMySchedulesRoute =
  DashboardDoctorMySchedulesRouteImport.update({
    id: '/my-schedules',
    path: '/my-schedules',
    getParentRoute: () => DashboardDoctorRouteRoute,
  } as any)
const DashboardDoctorAppointmentsRoute =
  DashboardDoctorAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DashboardDoctorRouteRoute,
  } as any)
const DashboardAdminSpecialitiesManagementRoute =
  DashboardAdminSpecialitiesManagementRouteImport.update({
    id: '/specialities-management',
    path: '/specialities-management',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminSchedulesManagementRoute =
  DashboardAdminSchedulesManagementRouteImport.update({
    id: '/schedules-management',
    path: '/schedules-management',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminPatientsManagementRoute =
  DashboardAdminPatientsManagementRouteImport.update({
    id: '/patients-management',
    path: '/patients-management',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminDoctorsManagementRoute =
  DashboardAdminDoctorsManagementRouteImport.update({
    id: '/doctors-management',
    path: '/doctors-management',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAppointmentsManagementRoute =
  DashboardAdminAppointmentsManagementRouteImport.update({
    id: '/appointments-management',
    path: '/appointments-management',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAdminsManagementRoute =
  DashboardAdminAdminsManagementRouteImport.update({
    id: '/admins-management',
    path: '/admins-management',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const ApiWeeklyAvailabilityGenerateRoute =
  ApiWeeklyAvailabilityGenerateRouteImport.update({
    id: '/api/weekly-availability/generate',
    path: '/api/weekly-availability/generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWeeklyAvailabilityCancelRoute =
  ApiWeeklyAvailabilityCancelRouteImport.update({
    id: '/api/weekly-availability/cancel',
    path: '/api/weekly-availability/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUserCreatePatientRoute = ApiUserCreatePatientRouteImport.update({
  id: '/api/user/create-patient',
  path: '/api/user/create-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreateDoctorRoute = ApiUserCreateDoctorRouteImport.update({
  id: '/api/user/create-doctor',
  path: '/api/user/create-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreateAdminRoute = ApiUserCreateAdminRouteImport.update({
  id: '/api/user/create-admin',
  path: '/api/user/create-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScheduleIdRoute = ApiScheduleIdRouteImport.update({
  id: '/api/schedule/$id',
  path: '/api/schedule/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/api/payment/webhook',
  path: '/api/payment/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentVerifyRoute = ApiPaymentVerifyRouteImport.update({
  id: '/api/payment/verify',
  path: '/api/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatientProfileRoute = ApiPatientProfileRouteImport.update({
  id: '/api/patient/profile',
  path: '/api/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatientIdRoute = ApiPatientIdRouteImport.update({
  id: '/api/patient/$id',
  path: '/api/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorSpecializationsRoute =
  ApiDoctorSpecializationsRouteImport.update({
    id: '/api/doctor/specializations',
    path: '/api/doctor/specializations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDoctorProfileRoute = ApiDoctorProfileRouteImport.update({
  id: '/api/doctor/profile',
  path: '/api/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorIdRoute = ApiDoctorIdRouteImport.update({
  id: '/api/doctor/$id',
  path: '/api/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorScheduleAvailableRoute =
  ApiDoctorScheduleAvailableRouteImport.update({
    id: '/api/doctor-schedule/available',
    path: '/api/doctor-schedule/available',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentIdRoute = ApiAppointmentIdRouteImport.update({
  id: '/api/appointment/$id',
  path: '/api/appointment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProfileRoute = ApiAdminProfileRouteImport.update({
  id: '/api/admin/profile',
  path: '/api/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIdRoute = ApiAdminIdRouteImport.update({
  id: '/api/admin/$id',
  path: '/api/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLandingDataIndexRoute =
  ApiPublicLandingDataIndexRouteImport.update({
    id: '/api/public/landing-data/',
    path: '/api/public/landing-data/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/consultation': typeof ConsultationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/doctor': typeof DashboardDoctorRouteRouteWithChildren
  '/dashboard/patient': typeof DashboardPatientRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/dev/': typeof DevIndexRoute
  '/api/admin/$id': typeof ApiAdminIdRoute
  '/api/admin/profile': typeof ApiAdminProfileRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/appointment/$id': typeof ApiAppointmentIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/doctor-schedule/available': typeof ApiDoctorScheduleAvailableRoute
  '/api/doctor/$id': typeof ApiDoctorIdRoute
  '/api/doctor/profile': typeof ApiDoctorProfileRoute
  '/api/doctor/specializations': typeof ApiDoctorSpecializationsRoute
  '/api/patient/$id': typeof ApiPatientIdRoute
  '/api/patient/profile': typeof ApiPatientProfileRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/schedule/$id': typeof ApiScheduleIdRoute
  '/api/user/create-admin': typeof ApiUserCreateAdminRoute
  '/api/user/create-doctor': typeof ApiUserCreateDoctorRoute
  '/api/user/create-patient': typeof ApiUserCreatePatientRoute
  '/api/weekly-availability/cancel': typeof ApiWeeklyAvailabilityCancelRoute
  '/api/weekly-availability/generate': typeof ApiWeeklyAvailabilityGenerateRoute
  '/dashboard/admin/admins-management': typeof DashboardAdminAdminsManagementRoute
  '/dashboard/admin/appointments-management': typeof DashboardAdminAppointmentsManagementRoute
  '/dashboard/admin/doctors-management': typeof DashboardAdminDoctorsManagementRoute
  '/dashboard/admin/patients-management': typeof DashboardAdminPatientsManagementRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/schedules-management': typeof DashboardAdminSchedulesManagementRoute
  '/dashboard/admin/specialities-management': typeof DashboardAdminSpecialitiesManagementRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRoute
  '/dashboard/doctor/my-schedules': typeof DashboardDoctorMySchedulesRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/patient/book-appointment': typeof DashboardPatientBookAppointmentRoute
  '/dashboard/patient/health-records': typeof DashboardPatientHealthRecordsRoute
  '/dashboard/patient/my-appointments': typeof DashboardPatientMyAppointmentsRoute
  '/dashboard/patient/my-prescriptions': typeof DashboardPatientMyPrescriptionsRoute
  '/dashboard/patient/payment-cancel': typeof DashboardPatientPaymentCancelRoute
  '/dashboard/patient/payment-history': typeof DashboardPatientPaymentHistoryRoute
  '/dashboard/patient/payment-success': typeof DashboardPatientPaymentSuccessRoute
  '/dashboard/patient/reviews': typeof DashboardPatientReviewsRoute
  '/api/admin/': typeof ApiAdminIndexRoute
  '/api/appointment/': typeof ApiAppointmentIndexRoute
  '/api/doctor-schedule/': typeof ApiDoctorScheduleIndexRoute
  '/api/doctor/': typeof ApiDoctorIndexRoute
  '/api/metadata/': typeof ApiMetadataIndexRoute
  '/api/patient/': typeof ApiPatientIndexRoute
  '/api/payment/': typeof ApiPaymentIndexRoute
  '/api/prescription/': typeof ApiPrescriptionIndexRoute
  '/api/review/': typeof ApiReviewIndexRoute
  '/api/schedule/': typeof ApiScheduleIndexRoute
  '/api/weekly-availability/': typeof ApiWeeklyAvailabilityIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/patient/': typeof DashboardPatientIndexRoute
  '/api/public/landing-data/': typeof ApiPublicLandingDataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/consultation': typeof ConsultationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/dev': typeof DevIndexRoute
  '/api/admin/$id': typeof ApiAdminIdRoute
  '/api/admin/profile': typeof ApiAdminProfileRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/appointment/$id': typeof ApiAppointmentIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/doctor-schedule/available': typeof ApiDoctorScheduleAvailableRoute
  '/api/doctor/$id': typeof ApiDoctorIdRoute
  '/api/doctor/profile': typeof ApiDoctorProfileRoute
  '/api/doctor/specializations': typeof ApiDoctorSpecializationsRoute
  '/api/patient/$id': typeof ApiPatientIdRoute
  '/api/patient/profile': typeof ApiPatientProfileRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/schedule/$id': typeof ApiScheduleIdRoute
  '/api/user/create-admin': typeof ApiUserCreateAdminRoute
  '/api/user/create-doctor': typeof ApiUserCreateDoctorRoute
  '/api/user/create-patient': typeof ApiUserCreatePatientRoute
  '/api/weekly-availability/cancel': typeof ApiWeeklyAvailabilityCancelRoute
  '/api/weekly-availability/generate': typeof ApiWeeklyAvailabilityGenerateRoute
  '/dashboard/admin/admins-management': typeof DashboardAdminAdminsManagementRoute
  '/dashboard/admin/appointments-management': typeof DashboardAdminAppointmentsManagementRoute
  '/dashboard/admin/doctors-management': typeof DashboardAdminDoctorsManagementRoute
  '/dashboard/admin/patients-management': typeof DashboardAdminPatientsManagementRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/schedules-management': typeof DashboardAdminSchedulesManagementRoute
  '/dashboard/admin/specialities-management': typeof DashboardAdminSpecialitiesManagementRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRoute
  '/dashboard/doctor/my-schedules': typeof DashboardDoctorMySchedulesRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/patient/book-appointment': typeof DashboardPatientBookAppointmentRoute
  '/dashboard/patient/health-records': typeof DashboardPatientHealthRecordsRoute
  '/dashboard/patient/my-appointments': typeof DashboardPatientMyAppointmentsRoute
  '/dashboard/patient/my-prescriptions': typeof DashboardPatientMyPrescriptionsRoute
  '/dashboard/patient/payment-cancel': typeof DashboardPatientPaymentCancelRoute
  '/dashboard/patient/payment-history': typeof DashboardPatientPaymentHistoryRoute
  '/dashboard/patient/payment-success': typeof DashboardPatientPaymentSuccessRoute
  '/dashboard/patient/reviews': typeof DashboardPatientReviewsRoute
  '/api/admin': typeof ApiAdminIndexRoute
  '/api/appointment': typeof ApiAppointmentIndexRoute
  '/api/doctor-schedule': typeof ApiDoctorScheduleIndexRoute
  '/api/doctor': typeof ApiDoctorIndexRoute
  '/api/metadata': typeof ApiMetadataIndexRoute
  '/api/patient': typeof ApiPatientIndexRoute
  '/api/payment': typeof ApiPaymentIndexRoute
  '/api/prescription': typeof ApiPrescriptionIndexRoute
  '/api/review': typeof ApiReviewIndexRoute
  '/api/schedule': typeof ApiScheduleIndexRoute
  '/api/weekly-availability': typeof ApiWeeklyAvailabilityIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/dashboard/patient': typeof DashboardPatientIndexRoute
  '/api/public/landing-data': typeof ApiPublicLandingDataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/consultation': typeof ConsultationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/doctor': typeof DashboardDoctorRouteRouteWithChildren
  '/dashboard/patient': typeof DashboardPatientRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/dev/': typeof DevIndexRoute
  '/api/admin/$id': typeof ApiAdminIdRoute
  '/api/admin/profile': typeof ApiAdminProfileRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/appointment/$id': typeof ApiAppointmentIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/doctor-schedule/available': typeof ApiDoctorScheduleAvailableRoute
  '/api/doctor/$id': typeof ApiDoctorIdRoute
  '/api/doctor/profile': typeof ApiDoctorProfileRoute
  '/api/doctor/specializations': typeof ApiDoctorSpecializationsRoute
  '/api/patient/$id': typeof ApiPatientIdRoute
  '/api/patient/profile': typeof ApiPatientProfileRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/schedule/$id': typeof ApiScheduleIdRoute
  '/api/user/create-admin': typeof ApiUserCreateAdminRoute
  '/api/user/create-doctor': typeof ApiUserCreateDoctorRoute
  '/api/user/create-patient': typeof ApiUserCreatePatientRoute
  '/api/weekly-availability/cancel': typeof ApiWeeklyAvailabilityCancelRoute
  '/api/weekly-availability/generate': typeof ApiWeeklyAvailabilityGenerateRoute
  '/dashboard/admin/admins-management': typeof DashboardAdminAdminsManagementRoute
  '/dashboard/admin/appointments-management': typeof DashboardAdminAppointmentsManagementRoute
  '/dashboard/admin/doctors-management': typeof DashboardAdminDoctorsManagementRoute
  '/dashboard/admin/patients-management': typeof DashboardAdminPatientsManagementRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/schedules-management': typeof DashboardAdminSchedulesManagementRoute
  '/dashboard/admin/specialities-management': typeof DashboardAdminSpecialitiesManagementRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRoute
  '/dashboard/doctor/my-schedules': typeof DashboardDoctorMySchedulesRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/patient/book-appointment': typeof DashboardPatientBookAppointmentRoute
  '/dashboard/patient/health-records': typeof DashboardPatientHealthRecordsRoute
  '/dashboard/patient/my-appointments': typeof DashboardPatientMyAppointmentsRoute
  '/dashboard/patient/my-prescriptions': typeof DashboardPatientMyPrescriptionsRoute
  '/dashboard/patient/payment-cancel': typeof DashboardPatientPaymentCancelRoute
  '/dashboard/patient/payment-history': typeof DashboardPatientPaymentHistoryRoute
  '/dashboard/patient/payment-success': typeof DashboardPatientPaymentSuccessRoute
  '/dashboard/patient/reviews': typeof DashboardPatientReviewsRoute
  '/api/admin/': typeof ApiAdminIndexRoute
  '/api/appointment/': typeof ApiAppointmentIndexRoute
  '/api/doctor-schedule/': typeof ApiDoctorScheduleIndexRoute
  '/api/doctor/': typeof ApiDoctorIndexRoute
  '/api/metadata/': typeof ApiMetadataIndexRoute
  '/api/patient/': typeof ApiPatientIndexRoute
  '/api/payment/': typeof ApiPaymentIndexRoute
  '/api/prescription/': typeof ApiPrescriptionIndexRoute
  '/api/review/': typeof ApiReviewIndexRoute
  '/api/schedule/': typeof ApiScheduleIndexRoute
  '/api/weekly-availability/': typeof ApiWeeklyAvailabilityIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/patient/': typeof DashboardPatientIndexRoute
  '/api/public/landing-data/': typeof ApiPublicLandingDataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/consultation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/api/$'
    | '/api/health'
    | '/dashboard/settings'
    | '/doctor/$id'
    | '/dev/'
    | '/api/admin/$id'
    | '/api/admin/profile'
    | '/api/ai/chat'
    | '/api/appointment/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/doctor-schedule/available'
    | '/api/doctor/$id'
    | '/api/doctor/profile'
    | '/api/doctor/specializations'
    | '/api/patient/$id'
    | '/api/patient/profile'
    | '/api/payment/checkout'
    | '/api/payment/verify'
    | '/api/payment/webhook'
    | '/api/schedule/$id'
    | '/api/user/create-admin'
    | '/api/user/create-doctor'
    | '/api/user/create-patient'
    | '/api/weekly-availability/cancel'
    | '/api/weekly-availability/generate'
    | '/dashboard/admin/admins-management'
    | '/dashboard/admin/appointments-management'
    | '/dashboard/admin/doctors-management'
    | '/dashboard/admin/patients-management'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/schedules-management'
    | '/dashboard/admin/specialities-management'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/my-schedules'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/patient/book-appointment'
    | '/dashboard/patient/health-records'
    | '/dashboard/patient/my-appointments'
    | '/dashboard/patient/my-prescriptions'
    | '/dashboard/patient/payment-cancel'
    | '/dashboard/patient/payment-history'
    | '/dashboard/patient/payment-success'
    | '/dashboard/patient/reviews'
    | '/api/admin/'
    | '/api/appointment/'
    | '/api/doctor-schedule/'
    | '/api/doctor/'
    | '/api/metadata/'
    | '/api/patient/'
    | '/api/payment/'
    | '/api/prescription/'
    | '/api/review/'
    | '/api/schedule/'
    | '/api/weekly-availability/'
    | '/dashboard/admin/'
    | '/dashboard/doctor/'
    | '/dashboard/patient/'
    | '/api/public/landing-data/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/consultation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/api/$'
    | '/api/health'
    | '/dashboard/settings'
    | '/doctor/$id'
    | '/dev'
    | '/api/admin/$id'
    | '/api/admin/profile'
    | '/api/ai/chat'
    | '/api/appointment/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/doctor-schedule/available'
    | '/api/doctor/$id'
    | '/api/doctor/profile'
    | '/api/doctor/specializations'
    | '/api/patient/$id'
    | '/api/patient/profile'
    | '/api/payment/checkout'
    | '/api/payment/verify'
    | '/api/payment/webhook'
    | '/api/schedule/$id'
    | '/api/user/create-admin'
    | '/api/user/create-doctor'
    | '/api/user/create-patient'
    | '/api/weekly-availability/cancel'
    | '/api/weekly-availability/generate'
    | '/dashboard/admin/admins-management'
    | '/dashboard/admin/appointments-management'
    | '/dashboard/admin/doctors-management'
    | '/dashboard/admin/patients-management'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/schedules-management'
    | '/dashboard/admin/specialities-management'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/my-schedules'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/patient/book-appointment'
    | '/dashboard/patient/health-records'
    | '/dashboard/patient/my-appointments'
    | '/dashboard/patient/my-prescriptions'
    | '/dashboard/patient/payment-cancel'
    | '/dashboard/patient/payment-history'
    | '/dashboard/patient/payment-success'
    | '/dashboard/patient/reviews'
    | '/api/admin'
    | '/api/appointment'
    | '/api/doctor-schedule'
    | '/api/doctor'
    | '/api/metadata'
    | '/api/patient'
    | '/api/payment'
    | '/api/prescription'
    | '/api/review'
    | '/api/schedule'
    | '/api/weekly-availability'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/api/public/landing-data'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/consultation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/api/$'
    | '/api/health'
    | '/dashboard/settings'
    | '/doctor/$id'
    | '/dev/'
    | '/api/admin/$id'
    | '/api/admin/profile'
    | '/api/ai/chat'
    | '/api/appointment/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/doctor-schedule/available'
    | '/api/doctor/$id'
    | '/api/doctor/profile'
    | '/api/doctor/specializations'
    | '/api/patient/$id'
    | '/api/patient/profile'
    | '/api/payment/checkout'
    | '/api/payment/verify'
    | '/api/payment/webhook'
    | '/api/schedule/$id'
    | '/api/user/create-admin'
    | '/api/user/create-doctor'
    | '/api/user/create-patient'
    | '/api/weekly-availability/cancel'
    | '/api/weekly-availability/generate'
    | '/dashboard/admin/admins-management'
    | '/dashboard/admin/appointments-management'
    | '/dashboard/admin/doctors-management'
    | '/dashboard/admin/patients-management'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/schedules-management'
    | '/dashboard/admin/specialities-management'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/my-schedules'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/patient/book-appointment'
    | '/dashboard/patient/health-records'
    | '/dashboard/patient/my-appointments'
    | '/dashboard/patient/my-prescriptions'
    | '/dashboard/patient/payment-cancel'
    | '/dashboard/patient/payment-history'
    | '/dashboard/patient/payment-success'
    | '/dashboard/patient/reviews'
    | '/api/admin/'
    | '/api/appointment/'
    | '/api/doctor-schedule/'
    | '/api/doctor/'
    | '/api/metadata/'
    | '/api/patient/'
    | '/api/payment/'
    | '/api/prescription/'
    | '/api/review/'
    | '/api/schedule/'
    | '/api/weekly-availability/'
    | '/dashboard/admin/'
    | '/dashboard/doctor/'
    | '/dashboard/patient/'
    | '/api/public/landing-data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ConsultationRoute: typeof ConsultationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DoctorIdRoute: typeof DoctorIdRoute
  DevIndexRoute: typeof DevIndexRoute
  ApiAdminIdRoute: typeof ApiAdminIdRoute
  ApiAdminProfileRoute: typeof ApiAdminProfileRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAppointmentIdRoute: typeof ApiAppointmentIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiDoctorScheduleAvailableRoute: typeof ApiDoctorScheduleAvailableRoute
  ApiDoctorIdRoute: typeof ApiDoctorIdRoute
  ApiDoctorProfileRoute: typeof ApiDoctorProfileRoute
  ApiDoctorSpecializationsRoute: typeof ApiDoctorSpecializationsRoute
  ApiPatientIdRoute: typeof ApiPatientIdRoute
  ApiPatientProfileRoute: typeof ApiPatientProfileRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiPaymentVerifyRoute: typeof ApiPaymentVerifyRoute
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
  ApiScheduleIdRoute: typeof ApiScheduleIdRoute
  ApiUserCreateAdminRoute: typeof ApiUserCreateAdminRoute
  ApiUserCreateDoctorRoute: typeof ApiUserCreateDoctorRoute
  ApiUserCreatePatientRoute: typeof ApiUserCreatePatientRoute
  ApiWeeklyAvailabilityCancelRoute: typeof ApiWeeklyAvailabilityCancelRoute
  ApiWeeklyAvailabilityGenerateRoute: typeof ApiWeeklyAvailabilityGenerateRoute
  ApiAdminIndexRoute: typeof ApiAdminIndexRoute
  ApiAppointmentIndexRoute: typeof ApiAppointmentIndexRoute
  ApiDoctorScheduleIndexRoute: typeof ApiDoctorScheduleIndexRoute
  ApiDoctorIndexRoute: typeof ApiDoctorIndexRoute
  ApiMetadataIndexRoute: typeof ApiMetadataIndexRoute
  ApiPatientIndexRoute: typeof ApiPatientIndexRoute
  ApiPaymentIndexRoute: typeof ApiPaymentIndexRoute
  ApiPrescriptionIndexRoute: typeof ApiPrescriptionIndexRoute
  ApiReviewIndexRoute: typeof ApiReviewIndexRoute
  ApiScheduleIndexRoute: typeof ApiScheduleIndexRoute
  ApiWeeklyAvailabilityIndexRoute: typeof ApiWeeklyAvailabilityIndexRoute
  ApiPublicLandingDataIndexRoute: typeof ApiPublicLandingDataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/doctor': {
      id: '/dashboard/doctor'
      path: '/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/patient/': {
      id: '/dashboard/patient/'
      path: '/'
      fullPath: '/dashboard/patient/'
      preLoaderRoute: typeof DashboardPatientIndexRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/doctor/': {
      id: '/dashboard/doctor/'
      path: '/'
      fullPath: '/dashboard/doctor/'
      preLoaderRoute: typeof DashboardDoctorIndexRouteImport
      parentRoute: typeof DashboardDoctorRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/weekly-availability/': {
      id: '/api/weekly-availability/'
      path: '/api/weekly-availability'
      fullPath: '/api/weekly-availability/'
      preLoaderRoute: typeof ApiWeeklyAvailabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule/': {
      id: '/api/schedule/'
      path: '/api/schedule'
      fullPath: '/api/schedule/'
      preLoaderRoute: typeof ApiScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/': {
      id: '/api/review/'
      path: '/api/review'
      fullPath: '/api/review/'
      preLoaderRoute: typeof ApiReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prescription/': {
      id: '/api/prescription/'
      path: '/api/prescription'
      fullPath: '/api/prescription/'
      preLoaderRoute: typeof ApiPrescriptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/': {
      id: '/api/payment/'
      path: '/api/payment'
      fullPath: '/api/payment/'
      preLoaderRoute: typeof ApiPaymentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patient/': {
      id: '/api/patient/'
      path: '/api/patient'
      fullPath: '/api/patient/'
      preLoaderRoute: typeof ApiPatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/': {
      id: '/api/metadata/'
      path: '/api/metadata'
      fullPath: '/api/metadata/'
      preLoaderRoute: typeof ApiMetadataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/': {
      id: '/api/doctor/'
      path: '/api/doctor'
      fullPath: '/api/doctor/'
      preLoaderRoute: typeof ApiDoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor-schedule/': {
      id: '/api/doctor-schedule/'
      path: '/api/doctor-schedule'
      fullPath: '/api/doctor-schedule/'
      preLoaderRoute: typeof ApiDoctorScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointment/': {
      id: '/api/appointment/'
      path: '/api/appointment'
      fullPath: '/api/appointment/'
      preLoaderRoute: typeof ApiAppointmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/': {
      id: '/api/admin/'
      path: '/api/admin'
      fullPath: '/api/admin/'
      preLoaderRoute: typeof ApiAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient/reviews': {
      id: '/dashboard/patient/reviews'
      path: '/reviews'
      fullPath: '/dashboard/patient/reviews'
      preLoaderRoute: typeof DashboardPatientReviewsRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/patient/payment-success': {
      id: '/dashboard/patient/payment-success'
      path: '/payment-success'
      fullPath: '/dashboard/patient/payment-success'
      preLoaderRoute: typeof DashboardPatientPaymentSuccessRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/patient/payment-history': {
      id: '/dashboard/patient/payment-history'
      path: '/payment-history'
      fullPath: '/dashboard/patient/payment-history'
      preLoaderRoute: typeof DashboardPatientPaymentHistoryRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/patient/payment-cancel': {
      id: '/dashboard/patient/payment-cancel'
      path: '/payment-cancel'
      fullPath: '/dashboard/patient/payment-cancel'
      preLoaderRoute: typeof DashboardPatientPaymentCancelRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/patient/my-prescriptions': {
      id: '/dashboard/patient/my-prescriptions'
      path: '/my-prescriptions'
      fullPath: '/dashboard/patient/my-prescriptions'
      preLoaderRoute: typeof DashboardPatientMyPrescriptionsRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/patient/my-appointments': {
      id: '/dashboard/patient/my-appointments'
      path: '/my-appointments'
      fullPath: '/dashboard/patient/my-appointments'
      preLoaderRoute: typeof DashboardPatientMyAppointmentsRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/patient/health-records': {
      id: '/dashboard/patient/health-records'
      path: '/health-records'
      fullPath: '/dashboard/patient/health-records'
      preLoaderRoute: typeof DashboardPatientHealthRecordsRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/patient/book-appointment': {
      id: '/dashboard/patient/book-appointment'
      path: '/book-appointment'
      fullPath: '/dashboard/patient/book-appointment'
      preLoaderRoute: typeof DashboardPatientBookAppointmentRouteImport
      parentRoute: typeof DashboardPatientRouteRoute
    }
    '/dashboard/doctor/prescriptions': {
      id: '/dashboard/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/dashboard/doctor/prescriptions'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsRouteImport
      parentRoute: typeof DashboardDoctorRouteRoute
    }
    '/dashboard/doctor/my-schedules': {
      id: '/dashboard/doctor/my-schedules'
      path: '/my-schedules'
      fullPath: '/dashboard/doctor/my-schedules'
      preLoaderRoute: typeof DashboardDoctorMySchedulesRouteImport
      parentRoute: typeof DashboardDoctorRouteRoute
    }
    '/dashboard/doctor/appointments': {
      id: '/dashboard/doctor/appointments'
      path: '/appointments'
      fullPath: '/dashboard/doctor/appointments'
      preLoaderRoute: typeof DashboardDoctorAppointmentsRouteImport
      parentRoute: typeof DashboardDoctorRouteRoute
    }
    '/dashboard/admin/specialities-management': {
      id: '/dashboard/admin/specialities-management'
      path: '/specialities-management'
      fullPath: '/dashboard/admin/specialities-management'
      preLoaderRoute: typeof DashboardAdminSpecialitiesManagementRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/schedules-management': {
      id: '/dashboard/admin/schedules-management'
      path: '/schedules-management'
      fullPath: '/dashboard/admin/schedules-management'
      preLoaderRoute: typeof DashboardAdminSchedulesManagementRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/patients-management': {
      id: '/dashboard/admin/patients-management'
      path: '/patients-management'
      fullPath: '/dashboard/admin/patients-management'
      preLoaderRoute: typeof DashboardAdminPatientsManagementRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/doctors-management': {
      id: '/dashboard/admin/doctors-management'
      path: '/doctors-management'
      fullPath: '/dashboard/admin/doctors-management'
      preLoaderRoute: typeof DashboardAdminDoctorsManagementRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/appointments-management': {
      id: '/dashboard/admin/appointments-management'
      path: '/appointments-management'
      fullPath: '/dashboard/admin/appointments-management'
      preLoaderRoute: typeof DashboardAdminAppointmentsManagementRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/admins-management': {
      id: '/dashboard/admin/admins-management'
      path: '/admins-management'
      fullPath: '/dashboard/admin/admins-management'
      preLoaderRoute: typeof DashboardAdminAdminsManagementRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/weekly-availability/generate': {
      id: '/api/weekly-availability/generate'
      path: '/api/weekly-availability/generate'
      fullPath: '/api/weekly-availability/generate'
      preLoaderRoute: typeof ApiWeeklyAvailabilityGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-availability/cancel': {
      id: '/api/weekly-availability/cancel'
      path: '/api/weekly-availability/cancel'
      fullPath: '/api/weekly-availability/cancel'
      preLoaderRoute: typeof ApiWeeklyAvailabilityCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/create-patient': {
      id: '/api/user/create-patient'
      path: '/api/user/create-patient'
      fullPath: '/api/user/create-patient'
      preLoaderRoute: typeof ApiUserCreatePatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/create-doctor': {
      id: '/api/user/create-doctor'
      path: '/api/user/create-doctor'
      fullPath: '/api/user/create-doctor'
      preLoaderRoute: typeof ApiUserCreateDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/create-admin': {
      id: '/api/user/create-admin'
      path: '/api/user/create-admin'
      fullPath: '/api/user/create-admin'
      preLoaderRoute: typeof ApiUserCreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule/$id': {
      id: '/api/schedule/$id'
      path: '/api/schedule/$id'
      fullPath: '/api/schedule/$id'
      preLoaderRoute: typeof ApiScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook': {
      id: '/api/payment/webhook'
      path: '/api/payment/webhook'
      fullPath: '/api/payment/webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/verify': {
      id: '/api/payment/verify'
      path: '/api/payment/verify'
      fullPath: '/api/payment/verify'
      preLoaderRoute: typeof ApiPaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patient/profile': {
      id: '/api/patient/profile'
      path: '/api/patient/profile'
      fullPath: '/api/patient/profile'
      preLoaderRoute: typeof ApiPatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patient/$id': {
      id: '/api/patient/$id'
      path: '/api/patient/$id'
      fullPath: '/api/patient/$id'
      preLoaderRoute: typeof ApiPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/specializations': {
      id: '/api/doctor/specializations'
      path: '/api/doctor/specializations'
      fullPath: '/api/doctor/specializations'
      preLoaderRoute: typeof ApiDoctorSpecializationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/profile': {
      id: '/api/doctor/profile'
      path: '/api/doctor/profile'
      fullPath: '/api/doctor/profile'
      preLoaderRoute: typeof ApiDoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/$id': {
      id: '/api/doctor/$id'
      path: '/api/doctor/$id'
      fullPath: '/api/doctor/$id'
      preLoaderRoute: typeof ApiDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor-schedule/available': {
      id: '/api/doctor-schedule/available'
      path: '/api/doctor-schedule/available'
      fullPath: '/api/doctor-schedule/available'
      preLoaderRoute: typeof ApiDoctorScheduleAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointment/$id': {
      id: '/api/appointment/$id'
      path: '/api/appointment/$id'
      fullPath: '/api/appointment/$id'
      preLoaderRoute: typeof ApiAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/profile': {
      id: '/api/admin/profile'
      path: '/api/admin/profile'
      fullPath: '/api/admin/profile'
      preLoaderRoute: typeof ApiAdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$id': {
      id: '/api/admin/$id'
      path: '/api/admin/$id'
      fullPath: '/api/admin/$id'
      preLoaderRoute: typeof ApiAdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landing-data/': {
      id: '/api/public/landing-data/'
      path: '/api/public/landing-data'
      fullPath: '/api/public/landing-data/'
      preLoaderRoute: typeof ApiPublicLandingDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteRouteChildren {
  DashboardAdminAdminsManagementRoute: typeof DashboardAdminAdminsManagementRoute
  DashboardAdminAppointmentsManagementRoute: typeof DashboardAdminAppointmentsManagementRoute
  DashboardAdminDoctorsManagementRoute: typeof DashboardAdminDoctorsManagementRoute
  DashboardAdminPatientsManagementRoute: typeof DashboardAdminPatientsManagementRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminSchedulesManagementRoute: typeof DashboardAdminSchedulesManagementRoute
  DashboardAdminSpecialitiesManagementRoute: typeof DashboardAdminSpecialitiesManagementRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminAdminsManagementRoute: DashboardAdminAdminsManagementRoute,
  DashboardAdminAppointmentsManagementRoute:
    DashboardAdminAppointmentsManagementRoute,
  DashboardAdminDoctorsManagementRoute: DashboardAdminDoctorsManagementRoute,
  DashboardAdminPatientsManagementRoute: DashboardAdminPatientsManagementRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminSchedulesManagementRoute:
    DashboardAdminSchedulesManagementRoute,
  DashboardAdminSpecialitiesManagementRoute:
    DashboardAdminSpecialitiesManagementRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardDoctorRouteRouteChildren {
  DashboardDoctorAppointmentsRoute: typeof DashboardDoctorAppointmentsRoute
  DashboardDoctorMySchedulesRoute: typeof DashboardDoctorMySchedulesRoute
  DashboardDoctorPrescriptionsRoute: typeof DashboardDoctorPrescriptionsRoute
  DashboardDoctorIndexRoute: typeof DashboardDoctorIndexRoute
}

const DashboardDoctorRouteRouteChildren: DashboardDoctorRouteRouteChildren = {
  DashboardDoctorAppointmentsRoute: DashboardDoctorAppointmentsRoute,
  DashboardDoctorMySchedulesRoute: DashboardDoctorMySchedulesRoute,
  DashboardDoctorPrescriptionsRoute: DashboardDoctorPrescriptionsRoute,
  DashboardDoctorIndexRoute: DashboardDoctorIndexRoute,
}

const DashboardDoctorRouteRouteWithChildren =
  DashboardDoctorRouteRoute._addFileChildren(DashboardDoctorRouteRouteChildren)

interface DashboardPatientRouteRouteChildren {
  DashboardPatientBookAppointmentRoute: typeof DashboardPatientBookAppointmentRoute
  DashboardPatientHealthRecordsRoute: typeof DashboardPatientHealthRecordsRoute
  DashboardPatientMyAppointmentsRoute: typeof DashboardPatientMyAppointmentsRoute
  DashboardPatientMyPrescriptionsRoute: typeof DashboardPatientMyPrescriptionsRoute
  DashboardPatientPaymentCancelRoute: typeof DashboardPatientPaymentCancelRoute
  DashboardPatientPaymentHistoryRoute: typeof DashboardPatientPaymentHistoryRoute
  DashboardPatientPaymentSuccessRoute: typeof DashboardPatientPaymentSuccessRoute
  DashboardPatientReviewsRoute: typeof DashboardPatientReviewsRoute
  DashboardPatientIndexRoute: typeof DashboardPatientIndexRoute
}

const DashboardPatientRouteRouteChildren: DashboardPatientRouteRouteChildren = {
  DashboardPatientBookAppointmentRoute: DashboardPatientBookAppointmentRoute,
  DashboardPatientHealthRecordsRoute: DashboardPatientHealthRecordsRoute,
  DashboardPatientMyAppointmentsRoute: DashboardPatientMyAppointmentsRoute,
  DashboardPatientMyPrescriptionsRoute: DashboardPatientMyPrescriptionsRoute,
  DashboardPatientPaymentCancelRoute: DashboardPatientPaymentCancelRoute,
  DashboardPatientPaymentHistoryRoute: DashboardPatientPaymentHistoryRoute,
  DashboardPatientPaymentSuccessRoute: DashboardPatientPaymentSuccessRoute,
  DashboardPatientReviewsRoute: DashboardPatientReviewsRoute,
  DashboardPatientIndexRoute: DashboardPatientIndexRoute,
}

const DashboardPatientRouteRouteWithChildren =
  DashboardPatientRouteRoute._addFileChildren(
    DashboardPatientRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardDoctorRouteRoute: typeof DashboardDoctorRouteRouteWithChildren
  DashboardPatientRouteRoute: typeof DashboardPatientRouteRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardDoctorRouteRoute: DashboardDoctorRouteRouteWithChildren,
  DashboardPatientRouteRoute: DashboardPatientRouteRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ConsultationRoute: ConsultationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  DoctorIdRoute: DoctorIdRoute,
  DevIndexRoute: DevIndexRoute,
  ApiAdminIdRoute: ApiAdminIdRoute,
  ApiAdminProfileRoute: ApiAdminProfileRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAppointmentIdRoute: ApiAppointmentIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiDoctorScheduleAvailableRoute: ApiDoctorScheduleAvailableRoute,
  ApiDoctorIdRoute: ApiDoctorIdRoute,
  ApiDoctorProfileRoute: ApiDoctorProfileRoute,
  ApiDoctorSpecializationsRoute: ApiDoctorSpecializationsRoute,
  ApiPatientIdRoute: ApiPatientIdRoute,
  ApiPatientProfileRoute: ApiPatientProfileRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiPaymentVerifyRoute: ApiPaymentVerifyRoute,
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
  ApiScheduleIdRoute: ApiScheduleIdRoute,
  ApiUserCreateAdminRoute: ApiUserCreateAdminRoute,
  ApiUserCreateDoctorRoute: ApiUserCreateDoctorRoute,
  ApiUserCreatePatientRoute: ApiUserCreatePatientRoute,
  ApiWeeklyAvailabilityCancelRoute: ApiWeeklyAvailabilityCancelRoute,
  ApiWeeklyAvailabilityGenerateRoute: ApiWeeklyAvailabilityGenerateRoute,
  ApiAdminIndexRoute: ApiAdminIndexRoute,
  ApiAppointmentIndexRoute: ApiAppointmentIndexRoute,
  ApiDoctorScheduleIndexRoute: ApiDoctorScheduleIndexRoute,
  ApiDoctorIndexRoute: ApiDoctorIndexRoute,
  ApiMetadataIndexRoute: ApiMetadataIndexRoute,
  ApiPatientIndexRoute: ApiPatientIndexRoute,
  ApiPaymentIndexRoute: ApiPaymentIndexRoute,
  ApiPrescriptionIndexRoute: ApiPrescriptionIndexRoute,
  ApiReviewIndexRoute: ApiReviewIndexRoute,
  ApiScheduleIndexRoute: ApiScheduleIndexRoute,
  ApiWeeklyAvailabilityIndexRoute: ApiWeeklyAvailabilityIndexRoute,
  ApiPublicLandingDataIndexRoute: ApiPublicLandingDataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
